# Generated by Django 5.0.3 on 2024-03-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Emprestimo', 'verbose_name_plural': 'Emprestimos'},
        ),
    ]
