# Generated by Django 5.0.3 on 2024-04-01 16:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fazeremprestimo', models.DateField(default=datetime.date.today, verbose_name='Data de empréstimo')),
                ('fazerdevolucao', models.DateField(default=datetime.date.today, verbose_name='Data de devolução')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leitor', verbose_name='Nome do leitor emprestado')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Nome do livro emprestado')),
            ],
        ),
    ]
